# Generated by Django 5.0.6 on 2024-06-14 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogs",
                to="blog.author",
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="blog",
            name="title",
            field=models.TextField(default="No title available"),
        ),
    ]
