# Generated by Django 5.0.6 on 2024-06-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_author_blog_content_blog_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.TextField(),
        ),
    ]
