# Generated by Django 5.0.6 on 2024-06-14 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0001_initial"),
        ("blog", "0003_alter_blog_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogs",
                to="author.author",
            ),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
