# Generated by Django 5.0.6 on 2024-06-17 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="blog",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.blog",
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="comments",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="comments",
            name="comment",
            field=models.TextField(default=""),
        ),
    ]
