# Generated by Django 5.0.6 on 2024-06-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0002_author_author_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="author_user_name",
            field=models.CharField(default="hello12", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="author",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="author",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="author",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="password",
            field=models.CharField(
                default="Hello@123456", max_length=128, verbose_name="password"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="author",
            name="author_email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
