# Generated by Django 5.0.6 on 2024-06-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0002_author_author_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="author_user_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
