# Generated by Django 5.0.6 on 2024-06-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0004_remove_author_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="author_user_name",
        ),
        migrations.RemoveField(
            model_name="author",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="author",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="author",
            name="password",
        ),
        migrations.AlterField(
            model_name="author",
            name="author_email",
            field=models.EmailField(max_length=254),
        ),
    ]
